title: Mohammad Mirmazloumi
description: IN, US
logo: /assets/img/my_photo.jpg
# show_downloads: true
# email: mohammad.mazloumi697@gmail.com
theme: jekyll-theme-minimal

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
# keywords: minimal light
# description: Remote Sensing and Geospatial.
# canonical: https://minimal-light-theme.yliu.me/

# # Links 
# google_scholar: https://scholar.google.com/citations?user=HYMdGjsAAAAJ&hl=en
# linkedin: https://www.linkedin.com/in/s-mohammad-mirmazloumi/
# researchgate: https://www.researchgate.net/profile/S-Mohammad-Mirmazloumi?ev=hdr_xprf

#avatar: /assets/img/my_photo.jpg

#remote_theme: yaoyao-liu/minimal-light
# The following files will be removed from the generated website.

