title: Mohammad Mirmazloumi
logo: /assets/img/my_photo.jpg
description: Remote Sensing and Geospatial
show_downloads: true
# email: mohammad.mazloumi697@gmail.com
# researchgate: https://www.researchgate.net/profile/S-Mohammad-Mirmazloumi?ev=hdr_xprf
theme: jekyll-theme-minimal
theme: null
remote_theme: null
